basePath: /api/adaptive
definitions:
  http.NextLessonRequest:
    properties:
      current_skill:
        type: string
      user_id:
        type: string
    required:
    - current_skill
    - user_id
    type: object
  http.NextLessonResponse:
    properties:
      content_type:
        type: string
      mastery_score:
        type: integer
      next_lesson_id:
        type: integer
      reason:
        type: string
    type: object
  response.Resp:
    properties:
      data: {}
      error_code:
        type: integer
      errors: {}
      message:
        type: string
    type: object
host: localhost:8084
info:
  contact: {}
  description: Adaptive Engine API documentation.
  title: Adaptive Engine API
  version: "1"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Show the service health and status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - Health
  /next-lesson:
    post:
      consumes:
      - application/json
      description: Returns recommended next lesson for a user based on current knowledge
        state.
      parameters:
      - description: Recommendation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.NextLessonRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Resp'
            - properties:
                data:
                  $ref: '#/definitions/http.NextLessonResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Resp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Resp'
      summary: Recommend next lesson
      tags:
      - Adaptive
schemes:
- http
swagger: "2.0"
