wipe=true                                 # Clean regeneration
output="internal/sqlboiler"                # Generated model location
pkgname="sqlboiler"                        # Package name
add-global-variant=true                   # Add global helper functions
add-enum-types=true                       # Generate enum types
no-hooks=false                            # Enable hooks for advanced features
no-tests=true                             # Skip test generation (for faster builds)
add-soft-deletes=true                     # Soft delete support
auto-columns=["created_at", "updated_at"] # Auto timestamp columns


[psql]
dbname = "learner_db"                   # Your app database name
host = "localhost"                     # Database server IP/hostname
port = 5432                   # Database port
user = "postgres"                     # Database user
pass = "postgres"                 # Database password
sslmode = "disable"                         # SSL mode (disable, require, verify-ca, verify-full)
schema = "public"   
blacklist = [
    "schema_migrations",                  # Migration tables
    "repmgr_*",                           # Repmgr tables
    "pg_stat_*",                          # PostgreSQL system tables
    "information_schema.*"                # System schema
]